import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:object_detect_test/domain/models/listing_model.dart';
import 'package:object_detect_test/data/repos/repositories.dart';
import 'package:object_detect_test/domain/models/offer_model.dart';
import 'package:object_detect_test/utils/result.dart';
import 'package:object_detect_test/utils/toaster.dart';

class ListingDetailContractorViewModel extends ChangeNotifier {
  final ListingRepository _listingRepository;
  final UserRepository _userRepository;
  final String listingId;

  ListingDetailContractorViewModel(this._listingRepository, this._userRepository, this.listingId) {
    _loadListing();
  }

  Listing? _listing;
  bool _isLoading = false;
  String? _errorMessage;

  Listing? get listing => _listing;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;

  Future<void> _loadListing() async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    final result = await _listingRepository.getListing(listingId);

    if (result is Failure) {
      _errorMessage = 'Failed to load listing: ${(result as Failure).message}';
      Toaster.showErrorFromFailure(result as Failure);
    } else {
      _listing = (result as Success).value;
    }

    _isLoading = false;
    notifyListeners();
  }

  Future<void> refreshListing() async {
    await _loadListing();
  }

  Future<void> createOffer(double price, DateTime selectedDate, String message) async {
    _isLoading = true;
    notifyListeners();

    try {
      final offer = Offer(
        id: '', // Will be generated by Firestore
        listingId: listingId,
        homeownerId: _listing!.author,
        contractorId: _userRepository.currentUser!.id,
        offerPrice: price,
        offerDate: Timestamp.fromDate(selectedDate),
        message: message.isEmpty ? '' : message,
        status: OfferStatus.pending,
        createdDate: Timestamp.now(),
      );
      final result = await _listingRepository.createListingOffer(listingId, _userRepository.currentUser!.id, offer);
      if (result is Failure) {
        _errorMessage = 'Failed to create offer: ${(result).message}';
        Toaster.showErrorFromFailure(result);
      }
    } catch (e) {
      _errorMessage = 'Failed to create offer: $e';
      rethrow;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }
}
