// Mocks generated by Mockito 5.4.6 from annotations
// in object_detect_test/test/ui/viewmodels/listings_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:object_detect_test/data/repos/repositories.dart' as _i2;
import 'package:object_detect_test/domain/models/listing_model.dart' as _i5;
import 'package:object_detect_test/domain/models/offer_model.dart' as _i7;
import 'package:object_detect_test/domain/models/user_model.dart' as _i8;
import 'package:object_detect_test/utils/result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ListingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockListingRepository extends _i1.Mock implements _i2.ListingRepository {
  MockListingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Listing>>> getListings(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getListings, [uid]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Listing>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Listing>>>(
                this,
                Invocation.method(#getListings, [uid]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Listing>>>);

  @override
  _i3.Future<_i4.Result<void>> createListing(_i5.Listing? listing) =>
      (super.noSuchMethod(
            Invocation.method(#createListing, [listing]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#createListing, [listing]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.Listing>> getListing(String? listingId) =>
      (super.noSuchMethod(
            Invocation.method(#getListing, [listingId]),
            returnValue: _i3.Future<_i4.Result<_i5.Listing>>.value(
              _i6.dummyValue<_i4.Result<_i5.Listing>>(
                this,
                Invocation.method(#getListing, [listingId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Listing>>);

  @override
  _i3.Future<_i4.Result<void>> deleteListing(String? listingId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteListing, [listingId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteListing, [listingId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateListingStatus(
    String? listingId,
    _i5.ListingStatus? newStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateListingStatus, [listingId, newStatus]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateListingStatus, [listingId, newStatus]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> createListingOffer(
    String? listingId,
    String? contractorId,
    _i7.Offer? offer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createListingOffer, [
              listingId,
              contractorId,
              offer,
            ]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#createListingOffer, [
                  listingId,
                  contractorId,
                  offer,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i7.Offer>>> getOffersForContractor(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getOffersForContractor, [uid]),
            returnValue: _i3.Future<_i4.Result<List<_i7.Offer>>>.value(
              _i6.dummyValue<_i4.Result<List<_i7.Offer>>>(
                this,
                Invocation.method(#getOffersForContractor, [uid]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i7.Offer>>>);

  @override
  _i3.Future<_i4.Result<Map<String, _i5.Listing>>> getListingsFromOffers(
    List<_i7.Offer>? offers,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getListingsFromOffers, [offers]),
            returnValue: _i3.Future<_i4.Result<Map<String, _i5.Listing>>>.value(
              _i6.dummyValue<_i4.Result<Map<String, _i5.Listing>>>(
                this,
                Invocation.method(#getListingsFromOffers, [offers]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<Map<String, _i5.Listing>>>);

  @override
  _i3.Future<_i4.Result<List<_i7.Offer>>> getOffersForHomeowner(
    String? homeownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOffersForHomeowner, [homeownerId]),
            returnValue: _i3.Future<_i4.Result<List<_i7.Offer>>>.value(
              _i6.dummyValue<_i4.Result<List<_i7.Offer>>>(
                this,
                Invocation.method(#getOffersForHomeowner, [homeownerId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i7.Offer>>>);

  @override
  _i3.Future<_i4.Result<void>> acceptOffer(
    String? offerId,
    String? listingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptOffer, [offerId, listingId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#acceptOffer, [offerId, listingId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> completeAppointment(
    String? offerId,
    String? listingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#completeAppointment, [offerId, listingId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#completeAppointment, [offerId, listingId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set currentUser(_i8.User? value) => super.noSuchMethod(
    Invocation.setter(#currentUser, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Stream<_i4.Result<_i8.User?>> userStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userStateChanges, []),
            returnValue: _i3.Stream<_i4.Result<_i8.User?>>.empty(),
          )
          as _i3.Stream<_i4.Result<_i8.User?>>);

  @override
  _i3.Future<_i4.Result<_i8.User?>> fetchUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUser, [uid]),
            returnValue: _i3.Future<_i4.Result<_i8.User?>>.value(
              _i6.dummyValue<_i4.Result<_i8.User?>>(
                this,
                Invocation.method(#fetchUser, [uid]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.User?>>);

  @override
  _i3.Future<_i4.Result<void>> createUserDocument(_i8.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUserDocument, [user]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#createUserDocument, [user]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateUserDocument(_i8.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserDocument, [user]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateUserDocument, [user]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
