// Mocks generated by Mockito 5.4.6 from annotations
// in object_detect_test/test/ui/viewmodels/registration_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:object_detect_test/data/repos/repositories.dart' as _i3;
import 'package:object_detect_test/domain/models/auth_model.dart' as _i6;
import 'package:object_detect_test/domain/models/user_model.dart' as _i8;
import 'package:object_detect_test/utils/result.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseAuth_0 extends _i1.SmartFake implements _i2.FirebaseAuth {
  _FakeFirebaseAuth_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseAuth get firebaseAuthInstance =>
      (super.noSuchMethod(
            Invocation.getter(#firebaseAuthInstance),
            returnValue: _FakeFirebaseAuth_0(
              this,
              Invocation.getter(#firebaseAuthInstance),
            ),
          )
          as _i2.FirebaseAuth);

  @override
  _i4.Stream<_i5.Result<_i6.Auth?>> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i4.Stream<_i5.Result<_i6.Auth?>>.empty(),
          )
          as _i4.Stream<_i5.Result<_i6.Auth?>>);

  @override
  _i4.Future<_i5.Result<void>> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> signUpWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [email, password]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#signUpWithEmail, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#sendPasswordResetEmail, [email]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> sendVerificationEmail() =>
      (super.noSuchMethod(
            Invocation.method(#sendVerificationEmail, []),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#sendVerificationEmail, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set currentUser(_i8.User? value) => super.noSuchMethod(
    Invocation.setter(#currentUser, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Stream<_i5.Result<_i8.User?>> userStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userStateChanges, []),
            returnValue: _i4.Stream<_i5.Result<_i8.User?>>.empty(),
          )
          as _i4.Stream<_i5.Result<_i8.User?>>);

  @override
  _i4.Future<_i5.Result<_i8.User?>> fetchUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUser, [uid]),
            returnValue: _i4.Future<_i5.Result<_i8.User?>>.value(
              _i7.dummyValue<_i5.Result<_i8.User?>>(
                this,
                Invocation.method(#fetchUser, [uid]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i8.User?>>);

  @override
  _i4.Future<_i5.Result<void>> createUserDocument(_i8.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUserDocument, [user]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#createUserDocument, [user]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> updateUserDocument(_i8.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserDocument, [user]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateUserDocument, [user]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);
}
