// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9OjkDYDJTrWfKWbg9TmXcvuZcbYgBHGs',
    appId: '1:521542213835:web:ffa3ed05f87fd2e29ebb4e',
    messagingSenderId: '521542213835',
    projectId: 'propertysense-544a4',
    authDomain: 'propertysense-544a4.firebaseapp.com',
    storageBucket: 'propertysense-544a4.firebasestorage.app',
    measurementId: 'G-BBH5TNTZ12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBunJKHT-ruvVVsI3EEoEgZJynH9bzNVm8',
    appId: '1:521542213835:android:34560368054bf4879ebb4e',
    messagingSenderId: '521542213835',
    projectId: 'propertysense-544a4',
    storageBucket: 'propertysense-544a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6oAbYNGTK3_KK_wI6_RfriCB_F6y-Cs',
    appId: '1:521542213835:ios:baa7c6bc230946699ebb4e',
    messagingSenderId: '521542213835',
    projectId: 'propertysense-544a4',
    storageBucket: 'propertysense-544a4.firebasestorage.app',
    iosBundleId: 'com.example.objectDetectTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo6oAbYNGTK3_KK_wI6_RfriCB_F6y-Cs',
    appId: '1:521542213835:ios:baa7c6bc230946699ebb4e',
    messagingSenderId: '521542213835',
    projectId: 'propertysense-544a4',
    storageBucket: 'propertysense-544a4.firebasestorage.app',
    iosBundleId: 'com.example.objectDetectTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9OjkDYDJTrWfKWbg9TmXcvuZcbYgBHGs',
    appId: '1:521542213835:web:f43685d14c242cef9ebb4e',
    messagingSenderId: '521542213835',
    projectId: 'propertysense-544a4',
    authDomain: 'propertysense-544a4.firebaseapp.com',
    storageBucket: 'propertysense-544a4.firebasestorage.app',
    measurementId: 'G-TE26NNTTBN',
  );
}
