name: Run Unit Tests

on:
  pull_request:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./object_detect_test
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  # Specify Flutter channel
          cache: true        # Enable caching for faster runs
      
      # - name: Install dependencies
      #   run: flutter pub get
      
      - name: Run unit tests
        run: flutter test